# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlanMyTrip' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PlanMyTrip
  pod 'Parse'
  pod 'AFNetworking'
  
  target 'PlanMyTripTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PlanMyTripUITests' do
    # Pods for testing
  end

end
